# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpu Transform
#'
#' Internal function
#'
#' @export
RcpuTransform <- function(x, xmod, len, sense, nlevels, ttype, filter, filterlen) {
    .Call('_wavecuda_RcpuTransform', PACKAGE = 'wavecuda', x, xmod, len, sense, nlevels, ttype, filter, filterlen)
}

